### ISSUE TITLE
Fluorine version 9.1

### ISSUE THREAD

**Issue by excilsploft** [solidfire/solidfire-sdk-python#22]
when I run this snippet 

for vol in sfe.list_volumes():
    print vol

I get the following stack trace

2017-05-03 16:11:34,340 - solidfire.Element - INFO - {"params": {}, "method": "ListVolumes", "id": 4}
---------------------------------------------------------------------------
TypeError                                 Traceback (most recent call last)
<ipython-input-7-cf2061fcaa1b> in <module>()
----> 1 for vol in sfe.list_volumes():
      2     print vol
      3

/usr/local/lib/python2.7/site-packages/solidfire/__init__.pyc in list_volumes(self, start_volume_id, limit, volume_status, accounts, is_paired, volume_ids)
   4658             ListVolumesResult,
   4659             params,
-> 4660             since=8
   4661         )
   4662

/usr/local/lib/python2.7/site-packages/solidfire/common/__init__.pyc in send_request(self, method_name, result_type, params, since, deprecated)
    643             raise ApiServerError(method_name, json.dumps(response))
    644         else:
--> 645             return model.extract(result_type, response['result'])
    646
    647     def _check_connection_type(self, method_name,

/usr/local/lib/python2.7/site-packages/solidfire/common/model.pyc in extract(typ, src)
     69     """
     70     if hasattr(typ, 'extract'):
---> 71         return_value = typ.extract(src, False)
     72     elif type(src) == typ:
     73         return_value = src

/usr/local/lib/python2.7/site-packages/solidfire/common/model.pyc in extract(cls, data, strict)
    326             elif prop.member_name() in data:
    327                 data_val = data[prop.member_name()]
--> 328                 ctor_dict[name] = prop.extract_from(data_val)
    329             # If we're dealing with an optional property which hasn't been provided
    330             elif prop.optional():

/usr/local/lib/python2.7/site-packages/solidfire/common/model.pyc in extract_from(self, data)
    152         if self._array:
    153             return [] if data is None else [extract(self._member_type, x) for x
--> 154                                             in data]
    155         if self._dictionaryType:
    156             newdict = dict()

/usr/local/lib/python2.7/site-packages/solidfire/common/model.pyc in extract(typ, src)
     69     """
     70     if hasattr(typ, 'extract'):
---> 71         return_value = typ.extract(src, False)
     72     elif type(src) == typ:
     73         return_value = src

/usr/local/lib/python2.7/site-packages/solidfire/common/model.pyc in extract(cls, data, strict)
    326             elif prop.member_name() in data:
    327                 data_val = data[prop.member_name()]
--> 328                 ctor_dict[name] = prop.extract_from(data_val)
    329             # If we're dealing with an optional property which hasn't been provided
    330             elif prop.optional():

/usr/local/lib/python2.7/site-packages/solidfire/common/model.pyc in extract_from(self, data)
    159             return newdict
    160         else:
--> 161             return None if data is None else extract(self._member_type, data)
    162
    163     def member_name(self):

/usr/local/lib/python2.7/site-packages/solidfire/common/model.pyc in extract(typ, src)
     74     elif typ == UUID:
     75         return_value = UUID(src)
---> 76     elif typ.__init__(src) is not None:
     77         return_value = typ.__init__(src)
     78     else:

TypeError: descriptor '__init__' requires a 'dict' object but received a 'list'

**Comment by ahaid** [comment]
Hello. Every method in the SolidFireElement class returns a *Result object. For example:
` result = sfe.list_volumes()` result will be a ListVolumesResult object. Inside there, you will find all the properties returned from the call. ListVolumesResult has a .volumes property you can iterate on.

The error you're getting is because you are trying to iterate over a dict when you should be iterating over a list.
Instead of this: `for vol in sfe.list_volumes():` 
Do this: `for vol in sf.list_volumes().volumes:`

**Comment by excilsploft** [comment]
then I should get an interation error, the reality is that prior versions of the api supported putting a list [] 
 vs an object {} into the attributes field. Flurorine no long supports this. Unfortunately, I have list data types in the attributes field rather than object data and your SDK breaks on the retrieval of data not the iteration.  I am able to iterate using the proper methods you outlined above only when I use direct json posts to update the attributes on the volume with an object and replace the list.

**Comment by ahaid** [comment]
Hi Kyle,

I understand the problem a bit better now and I have re-created it. You're right that we only support dict types in the attributes field now. I have a workaround for you and I'm hoping you use it to change the attributes of all your volumes into dicts. 

This code uses the python SDK to retrieve all volumes, pull out the lists in the attributes property, converts it into a dict, then sends it back. 

```
from solidfire.factory import ElementFactory

e = ElementFactory.create("mvip-of-cluster", "username", "password")
result = e.invoke_sfapi("ListActiveVolumes")
for vol in result["volumes"]:
    e.modify_volume(vol["volumeID"], attributes={"list": vol["attributes"]})
```

The workaround is to call "invoke-sfapi". This is a generic API method caller that returns a dict hydrated with whatever json the API sent back. It doesn't attempt to deserialize it into the defined types so will not throw the exceptions you're seeing.

I hope this helps. I'm reopening this issue while you evaluate this. Please comment back here with any feedback.

**Comment by excilsploft** [comment]
yes this works great thanks!
