### ISSUE TITLE
Use friendlier build instructions?

### ISSUE THREAD

**Issue by scaleoutsean** [solidfire/solidfire-sdk-python#25]
Maybe we can use the user-friendlier way to clone the repo (in README)?

```
/home/solidfire# git clone git@github.com:solidfire/solidfire-sdk-python.git
Cloning into 'solidfire-sdk-python'...
Permission denied (publickey).
fatal: Could not read from remote repository.

Please make sure you have the correct access rights
and the repository exists.

/home/solidfire# git clone https://github.com/solidfire/solidfire-sdk-python.git
Cloning into 'solidfire-sdk-python'...
remote: Counting objects: 7952, done.
remote: Compressing objects: 100% (24/24), done.
Receiving objects:   8% (637/7952), 108.01 KiB | 39.00 KiB/s
```

**Comment by ahaid** [comment]
Those messages are controlled by git. We have no way of changing them. Sorry Sean.

**Comment by scaleoutsean** [comment]
Right, but I mean `git clone git@github.com:solidfire/solidfire-sdk-python.git` creates an error.

Whereas if we switch to the simpler HTTPS, `git clone https://github.com/solidfire/solidfire-sdk-python.git`, it works fine.

**Comment by ahaid** [comment]
Thanks for checking ahead of time before changing this. I'd rather leave it the way it is. Most people who use git have SSH keys set up so they don't have to enter credentials every time.

**Comment by scaleoutsean** [comment]
Sounds good, closing.
