### ISSUE TITLE
Optional variables cannot be defined the way they are displayed

### ISSUE THREAD

**Issue by DirtyCajunRice** [solidfire/solidfire-sdk-python#28]
Python 3.5.2 does not allow you to create an "Object" as stated in the documentation and video.

example:
```
qos = QoS(burst_iops=15000, max_iops=15000, min_iops=50)
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
NameError: name 'QoS' is not defined
```

I dont see why it cannot accept JSON formatted data as the api is designed to recieve, e.g.:
```
{
 'QoS':
    {
     'burstIOPS': 15000,
     'maxIOPS': 15000,
     'minIOPS': 50
    }
}
```

This applies to every single object you have as a variable=OPTIONAL argument. account chap initiators etc.

Thanks,

**Comment by ahaid** [comment]
You need to import the QoS class from the solidfire package at the top of your file.

`from solidfire import QoS`

Or you can import all the models with:

`from solidfire import *`

**Comment by DirtyCajunRice** [comment]
So that works, But your documentation is vague and references it as an object not as a class. A great example is when someone wants to add chap to a new account:
http://solidfire-sdk-python.readthedocs.io/en/latest/solidfire.html#create-an-account
you only show importing ElementFactory and that would not work. If you had from solidfire import CHAPSecret it would have been intuitive.

**Comment by ahaid** [comment]
You are right. The documentation for the examples and the necessary imports is poor. We will get it updated before the next release.

**Comment by DirtyCajunRice** [comment]
Thanks! Appreciate the swift replies. Ill close this out.
