### ISSUE TITLE
PythonHosted Docs Broken

### ISSUE THREAD

**Issue by DirtyCajunRice** [solidfire/solidfire-sdk-python#29]
https://pythonhosted.org/solidfire-sdk-python/ returns Not Found

**Comment by ahaid** [comment]
The docs have been moved to http://solidfire-sdk-python.readthedocs.io/. 

The links in the root README have been updated to reflect the new location.

**Comment by DirtyCajunRice** [comment]
awesome! Added some documentation issues in the other issue, ill close this out. Thanks
