### ISSUE TITLE
Unable to find SolidfireElement

### ISSUE THREAD

**Issue by syed** [solidfire/solidfire-sdk-python#3]
Hi Guys, 

I was trying out the python SDK for a project of mine and ran into some issues. I initially deployed the `master` branch but found the setup.py to be broken and submitted PR#1. I then found out that there is a `develop` branch which is more current and tried that as well but, it too failed. 

I am following the setps listed on https://github.com/solidfire/solidfire-sdk-python/tree/develop

Here is the error that I am getting:

```
sahmed@beta-t2-acs01: ~/vdi-lun-testing (master) $ python
Python 2.6.6 (r266:84292, Jul 23 2015, 15:22:56)
[GCC 4.4.7 20120313 (Red Hat 4.4.7-11)] on linux2
Type "help", "copyright", "credits" or "license" for more information.
>>> from solidfire import Element
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
ImportError: No module named solidfire
>>> 
sahmed@beta-t2-acs01: ~/vdi-lun-testing (master) $ echo $PYTHONPATH
/home/sahmed/solidfire-sdk-python/
sahmed@beta-t2-acs01: ~/vdi-lun-testing (master) 
```

**Comment by jason-womack** [comment]
The solidfire.element module has only recently been checked in as the code is generated and was in a constant state of flux. We are nearing the release of 1.0.0, and I am inviting you to checkout the release/1.0.0 branch if you would like a preview.
