### ISSUE TITLE
Cannot pass anything to CHAPSecret class 

### ISSUE THREAD

**Issue by DirtyCajunRice** [solidfire/solidfire-sdk-python#31]
code:
```
customer = "Customer A"
initiator_chap = "asdfasdfasdfasdf"
target_chap = "fdsafdsafdsafdsa"
account = server.add_account(username=customer,
                                         initiator_secret=CHAPSecret(initiator_chap),
                                         target_secret=CHAPSecret(target_chap)
                                         )
```
Error:
```
Traceback (most recent call last):
  File "quantum.py", line 75, in <module>
    NEW_SOLIDFIRE_STORAGE.api_push()
  File "C:\Nicks Files\Quantum\quantum\storage\solidfire.py", line 43, in api_push
    initiator_secret=CHAPSecret(initiator_chap),
TypeError: __init__() takes 1 positional argument but 2 were given
```

This leads me to believe that although your class `__init__` for CHAPSecret defines **kwargs, it is not actually allowing any string or object to be passed to the class.

**Comment by joel-arthur** [comment]
CHAPSecret needs to be initialized with the 'secret' parameter:

initiator_secret=CHAPSecret(secret="asdfasdfasdfasdf")

This is obviously not intuitive and also not possible to discover without looking in the source code. We will get this corrected for the next release. I will also update the example docs to show how to do this for now.

**Comment by DirtyCajunRice** [comment]
Closing as my issue is technically resolved. Thanks
