### ISSUE TITLE
where are solidfire.models?

### ISSUE THREAD

**Issue by plz** [solidfire/solidfire-sdk-python#33]
I use https://github.com/cbiebers/solidfire-graphite-collector, and since I upgraded to 1.5 solidfire-python-sdk I get errors like:

`Traceback (most recent call last):
  File "/usr/local/git_tree/storage/tools/solidfire_collector.py", line 26, in <module>
    from solidfire.factory import ElementFactory
  File "/opt/blue-python/2.7/lib/python2.7/site-packages/solidfire/__init__.py", line 14, in <module>
    from solidfire.adaptor import ElementServiceAdaptor
  File "/opt/blue-python/2.7/lib/python2.7/site-packages/solidfire/adaptor/__init__.py", line 10, in <module>
    from solidfire.adaptor.schedule_adaptor import ScheduleAdaptor
  File "/opt/blue-python/2.7/lib/python2.7/site-packages/solidfire/adaptor/schedule_adaptor.py", line 14, in <module>
    from solidfire.models import Schedule, Frequency, ScheduleInfo, GetScheduleResult, ListSchedulesResult, \
ImportError: No module named models`

So was this removed from the module?

Also why is there no __init__.py in the solidfire/ directory?

**Comment by ahaid** [comment]
Hi @plz, How did you upgrade to 1.5? If you are cloning this repo, you're not getting all the code. This repo doesn't have the auto-generated files that end up in our deployed version. Instead, you should `pip install solidfire-sdk-python` or it should be referenced via a requirements.txt file in the graphite collector repo.

**Comment by plz** [comment]
I use the .tar.gz from the releases section(https://github.com/solidfire/solidfire-sdk-python/releases). The 1.4 used to have those autogenerated files. Any ideas why they are no longer in the 1.5 release?

**Comment by ahaid** [comment]
We removed them from this repo because they were cluttering up the commit history. We weren't aware anyone was pulling them as a .zip. I can produce one for you and email it to you or you can `pip install solidfire.sdk-python`. Which would you prefer?

**Comment by plz** [comment]
if you can send them to me I'd appreciate. We don't pip on our env, just build custom rpms, and yeah, was using the tar.gz's from the releases :)

**Comment by ahaid** [comment]
I sent it to the gmail address in your github profile.

**Comment by arjun960** [comment]
As the above response resolves your query, closing the issue.
