### ISSUE TITLE
Adding a new function to fail drives Referencing the API documentation for Element OS V9.0

### ISSUE THREAD

**Issue by zomzom96** [solidfire/solidfire-sdk-python#34]
```
# This function is an addition to the SolidFire SDK library
# to the __init__.py file that resides in the /solidfire directory 
# Function purpose(s): to fail the drive(s) that are passed in
def fail_drives(self, drive, force = True, ) :
    """ This function is to fail drives as a part of the IOP testcases
        :param drive: [required] Required parameter to locate the correct drive
        :type drive: str

        :param force: [required] Required parameter to force fail the drive
                      Defaults to True if no input given
        :type force: bool

    """

    self._check_connection_type("fail_drives", "Cluster")

    params = {
        "force"  : "true",
        "service" : "block",
        "action" : "stop",
    }
    return self.send_request(
        'RestartServices'.
            AsyncHandleResult,
        params,
        since = 5.0
    )

```
**NOTE:** we might need to include the service ID too to locate the correct drive 

This is needed in case you need to fail a drive for either testing purposes or other reasons. 

Thanks

**Comment by ahaid** [comment]
FailDrive isn't an API method. The Python SDK exposes API methods 1:1 with functions in the SDK. RestartServices is supported already. This would be a good candidate for a new class that offers helper functions but the way it's implemented here doesn't take the drive parameter into consideration when it restarts services so I don't see how it actually fails a drive.

**Comment by zomzom96** [comment]
I know that from the shell we need to specify the service ID example:

JSON format parameters  
[
 {"service":"block", "serviceID":54},
 {"service":"block", "serviceID":47},
]

I think we'd have to query the service ID first from the code itself and pass it into this fail_drives function as a parameter, or we can have this function do that for the user when he passes the node and drive ID

right now it takes the drive ID as a parameter

**Comment by arjun960** [comment]
@zomzom96 1. "FailDrive" is not an API method. 
2. RestartServices API which you are using in the above code is used to start, stop and restart services, but not for failing drive. 
3. Regarding the request of including serviceID parameter: You can use 'service'(service name)  parameter to modify any service state instead of serviceID.

Can you please elaborate more on the issue so that we can provide you for proper help ?

Note: Please refer API documentation for API details and SDK documentation for SDK stuff.
