### ISSUE TITLE
SDK 1.5 Exception._err_json does not contain a JSON, at least for xAsyncHandleDoesNotExist

### ISSUE THREAD

**Issue by ejortegau** [solidfire/solidfire-sdk-python#35]
Hi:

We had this piece of code:
`json.loads(e._err_json)['error']['name'] == 'xAsyncHandleDoesNotExist'  # e is a caught exception`
Which started failing after we upgraded from 1.4 to 1.5. Upon further investigation, ti seems like e._err_json is not actually a JSON string anymore, but instead, just a text string. So either _err_json probably needs to be renamed, or its contents should be made back into a JSON string. Thanks!

**Comment by Salmanius** [comment]
Thank you for pointing this out. We made some earlier changes for better error messages, and did not realize this caused problems. This has been fixed in our 1.6 release.

**Comment by labazza** [comment]
@Salmanius  where would be possible to get the .tgz for reease 1.6?

**Comment by Salmanius** [comment]
Currently the 1.6 release will be _at least_ 12 weeks from now but I can supply a current tested version of our 1.6 build. 

**Please Note:** Extensive testing has not been done of this most recent change. If you do find problems, please let us know about them (ie github issues), but be aware there is no support for this version currently.

Please email me at chris.cochran2@netapp.com and I can send you that file.

**Comment by labazza** [comment]
@Salmanius it seems version 1.6 does indeed solve the problem with not decodable Json.
So during ApiServerError we are able to decode e.error_name == 'xDBVersionMismatch' after patching the sdk to 1.6
this worked on about 53 instances where the exception has occurred

**Comment by arjun960** [comment]
As the above response resolves your query, closing the issue.
