### ISSUE TITLE
is read_timeout a thing?

### ISSUE THREAD

**Issue by plz** [solidfire/solidfire-sdk-python#36]
According to http://solidfire-sdk-python.readthedocs.io/en/latest/solidfire.html#timeouts there is a read_timeout parameter that can be set up, but i failed to find references to it in the code. Is timeout paramenter actually used for connect, and read timeouts? 

`AttributeError: 'Element' object has no attribute 'read_timeout'`

**Comment by ahaid** [comment]
@plz, You are right. A few versions ago we renamed `read_timeout` to `timeout`. It represents the time to wait for a response before timeout. This SDK also has `connect_timeout` which is the time for a connection to be established before timeout.

**Comment by arjun960** [comment]
As the above response resolves your query, closing the issue.
