### ISSUE TITLE
Proxy error

### ISSUE THREAD

**Issue by prasathcse** [solidfire/solidfire-sdk-python#40]
Package: solidfire-sdk-python 1.5.0.87

Could you please help us where we can disable the proxy  to fix this error

>>> sfe = ElementFactory.create("<IP>","test","acc")
2018-02-23 15:09:59,714 - solidfire.Element - INFO - {"params": {}, "method": "GetAPI", "id": 1}
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/usr/lib/python2.7/site-packages/solidfire/factory.py", line 87, in create
    api = element.get_api()
  File "/usr/lib/python2.7/site-packages/solidfire/__init__.py", line 668, in get_api
    since=1.0
  File "/usr/lib/python2.7/site-packages/solidfire/common/__init__.py", line 622, in send_request
    raise ApiConnectionError(e)
solidfire.common.ApiConnectionError: HTTPSConnectionPool(host='10.204.30.134', port=443): Max retries exceeded with url: /json-rpc/7.0 (Caused by ProxyError('Cannot connect to proxy.', error('Tunnel connection failed: 403 Forbidden',)))

**Comment by prasathcse** [comment]
How we can disable it

**Comment by ahaid** [comment]
The problem here is that you're not specifying an IP address or URL for the target parameter on line 1.

This will not work:

    sfe = ElementFactory.create("","test","acc")

Do this:

    sfe = ElementFactory.create("1.1.1.1","test","acc")

**Comment by prasathcse** [comment]
I did with the IP-address  still it throw the same error

**Comment by ahaid** [comment]
You used your IP address correct? Not 1.1.1.1?

**Comment by prasathcse** [comment]
yep thats correct when i use the correct SolidFire IP-address

**Comment by ahaid** [comment]
The python SDK doesn't use an proxy. There is probably an issue with the networking between the client and SolidFire cluster. Can you ping it successfully from the client?

**Comment by prasathcse** [comment]
We need to disable the proxy environment variable by unset http_proxy and unset https_proxy commands
