### ISSUE TITLE
Array 'Type Hints' are broken.

### ISSUE THREAD

**Issue by jason-womack** [solidfire/solidfire-sdk-python#41]
The type hints is broken with the SDK because the type of the Array is provided instead of the Array of that type i.e. [Type]

This is true for all arrays in the SDK.

**_example:_**
"""
    ListPendingNodesResult  
        :param pending_nodes: [required]  
        :type pending_nodes: **PendingNode** # should be **[PendingNode]**
"""
pending_nodes = data_model.property(
    "pendingNodes", PendingNode,
    **array=True**, optional=False,
    documentation=""" """,
    dictionaryType=None
)

**Comment by arjun960** [comment]
@jason-womack We have addressed and resolved this issue and the fix will be available in the next SDK release
