### ISSUE TITLE
Missing ClusterStructure API calls. 

### ISSUE THREAD

**Issue by Salmanius** [solidfire/solidfire-sdk-python#45]
Steve Barrera pointed out that we do not have Get or SetClusterStructure API calls. There may be more now that there is an official 11.0 api guide, but CS is missing.

**Comment by arjun960** [comment]
Get or SetClusterStructure APIs are available since 10.3version and SDK 1.7 for Java, Python, Dotnet(CS) and Powershell, please refer element APIs reference guide for more information.
https://library.netapp.com/ecm/ecm_download_file/ECMLP2848201

**Comment by arjun960** [comment]
@Salmanius As issue is resolved hence closing this issue.
