### ISSUE TITLE
list_network_interfaces does not support force parameter

### ISSUE THREAD

**Issue by natedh** [solidfire/solidfire-sdk-python#46]
list_network_interfaces() doesn't currently support the force parameter in the Python SDK. 
Would it be possible to add it so that the SDK supports the same parameters as the SolidFire API?
From the API:

> ListNetworkInterfaces
The ListNetworkInterfaces API method allows you to retrieve information about each network interface on a node. This API method is intended for use on individual nodes; userid and password authentication is required for access to individual nodes. However, you can use this method on the cluster if the force=true parameter is included in the method call. When used on the cluster, all interfaces are listed.

**Comment by arjun960** [comment]
@natedh The force parameter which is working through postman is an internal/private parameter and is intended only for development/testing purposes. So the SDK does not expose these parameters.
