### ISSUE TITLE
Support for connecting  to SolidFire API with access token instead of password

### ISSUE THREAD

**Issue by kalyanbhonagiri16** [solidfire/solidfire-sdk-python#47]
RIght now we connect to the API using username/password. can we have support to connect to solidfire using API access token.

**Comment by scaleoutsean** [comment]
If you upgrade to v12, you can create LDAP accounts and use MFA - https://docs.netapp.com/sfe-120/topic/com.netapp.doc.sfe-ug/GUID-D2902268-BF48-4F48-8A88-FD172BA1F653.html?resultof=%22%6d%66%61%22%20

**Comment by arjun960** [comment]
As the above response resolves your query, closing the issue.
