### ISSUE TITLE
Undocumented behavior with null values 

### ISSUE THREAD

**Issue by scaleoutsean** [solidfire/solidfire-sdk-python#50]
driveStats object for MD drive returns `null` value:

```json
        "driveStats": [
            {
                "activeSessions": 2,
                "driveID": 1,
                "failedDieCount": 0,
                "lifeRemainingPercent": 100,
                "lifetimeReadBytes": 0,
                "lifetimeWriteBytes": 0,
                "powerOnHours": 0,
                "readBytes": 891593953280,
                "readOps": 59037924,
                "reallocatedSectors": 0,
                "reserveCapacityPercent": 100,
                "timestamp": "2020-02-05T17:09:50.537582Z",
                "totalCapacity": 14495514624,
                "uncorrectableErrors": 0,
                "usedCapacity": null,                    <=========
                "usedMemory": 6296129536,
                "writeBytes": 890276257792,
                "writeOps": 28493320
            }]
```

However with PythonSDK `list_drive_stats().to_json()` omits the key entirely.

```shell
>>> lds = sfe.list_drive_stats().to_json()['driveStats']
2020-02-06 01:11:57,446 - solidfire.Element - INFO - {"method": "ListDriveStats", "id": 5, "params": {}}
[{'activeSessions': 2, 'driveID': 1, 'failedDieCount': 0, 'lifeRemainingPercent': 100, 'lifetimeReadBytes': 0, 'lifetimeWriteBytes': 0, 'powerOnHours': 0, 'readBytes': 891594129408, 'readOps': 59037967, 'reallocatedSectors': 0, 'reserveCapacityPercent': 100, 'timestamp': '2020-02-05T17:11:58.355498Z', 'totalCapacity': 14495514624, 'usedMemory': 6296166400, 'writeBytes': 890276433920, 'writeOps': 28493363}] 
```
Looking at the result in dictionary format, it's there:

```shell
>>> sfe.list_drive_stats()
... used_capacity=None ...
```
Now, [the SDK docs](https://solidfire-sdk-python.readthedocs.io/en/latest/solidfire.html?highlight=listdrivestats#solidfire.models.DriveStats) don't say this value is mandatory but Element API Reference Guide for v11 (November 2018 | 215-13565_A0) says nothing about that (`driveStats` object, page 171) - supposedly `usedCapacity` an integer value for any type of drive: 

`usedCapacity - Used capacity of the drive, in bytes. integer`

Is that empty value a Metadata Drive thing? MD drives also have `activeSessions` (same `driveStats` object description) and that is properly documented:

`activeSessions: Number of iSCSI sessions currently using this drive (only present for metadata drives).`

Can the SDK be modified to return `0` instead of `None`, or can the API Guide be improved to note that value `None` may be returned for MD drives (or under some special conditions - I don't know what those might be)?

Problem I ran into was the same as described [here](https://stackoverflow.com/questions/3930188/how-to-convert-nonetype-to-int-or-string#comment30239860_3930374) - messes up key enumeration. I just spent 2 hours looking at wrong places for possible issue with code...

**Comment by arjun960** [comment]
@scaleoutsean The Python SDK is showing the expected behavior where the 'usedCapacity' parameter is coming as None by default. It cant be changed to zero because it might break the scripts for other users.

Since the usedCapacity parameter is an integer, we will modify the apiguide that the "usedCapacity" parameter can have default possible value of None(null).
